"""A run report that keeps four kinds of finding apart.

A recorded run supports four different statements, and a report that blends them claims
more than any one of them does:

- **Service outcomes**: what each service class received, and which requirements were met,
  violated or left inconclusive.
- **Coordination stability**: how the controller behaved. It consults no service outcome,
  so a stable controller that failed its requirements appears as stable and failing.
- **Missing evidence**: what the run could not see or could not score. Unknown stays
  unknown here, and is not counted as a pass anywhere else.
- **Privileged-information results**: anything that rests on simulator truth. A verdict
  derived from truth is a reference, not evidence a deployed controller could produce, so
  it is labelled where it is reported rather than left for a reader to infer.

Everything is read from the artifact store, so the report can be regenerated by anyone
holding a run's artifacts and cannot depend on anything the run did not record. Nothing
here reads the model.
"""

from .contracts import Record
from .metrics import measurements, read_run

REPORT_VERSION = "run-report-v1"


def stability_limits(period_s):
    """The behavioural bounds a short run is judged against.

    The nominal `stability_window_s=10` is longer than a demonstration run, so the window
    is two decision periods. The churn limits are the nominal ones. All are declared and
    uncalibrated, and every report states the values it used.
    """
    return {"stability_window_s": period_s * 2, "action_churn_limit": 2,
            "claim_churn_limit": 4, "stale_retry_limit": 2}


def _payloads(store, dataset_id):
    return [Record.from_dict(m.data["payload"]) for m in store.messages(dataset_id)]


def _epochs(store):
    """How many decision epochs the run recorded, counted from its diagnosis datasets."""
    present = set(store.dataset_ids())
    count = 0
    while f"dataset:diagnosis:{count}" in present:
        count += 1
    return count


def _period(store, epochs):
    if epochs < 2:
        return None
    first, second = (store.invocation(f"diagnosis:{index}").data["decision_watermark_s"]
                     for index in (0, 1))
    return second - first


def service_outcomes(store):
    """Per-service measurements and the verdict on each requirement."""
    present = set(store.dataset_ids())
    measured, cohorts = {}, []
    if "dataset:result" in present:
        for payload in _payloads(store, "dataset:result"):
            if payload.kind != "ResultRecord":
                continue
            cohorts = payload.data["cohorts"]
            for m in payload.data["measurements"]:
                measured.setdefault(m["service"], {})[m["metric"]] = {
                    "value": m["value"], "quality": m["quality"],
                    "numerator": m["numerator"], "denominator": m["denominator"]}
    claims = []
    regime = None
    if "dataset:assurance" in present:
        regime = store.dataset("dataset:assurance").data["information_regime"]
        for payload in _payloads(store, "dataset:assurance"):
            if payload.kind == "AssuranceReport":
                claims = [{"requirement_id": c["requirement_id"], "verdict": c["verdict"],
                           "reason": (c["reason"] or {}).get("code")} for c in payload.data["claims"]]
    tally = {verdict: sum(c["verdict"] == verdict for c in claims)
             for verdict in ("met", "violated", "inconclusive")}
    return {"by_service": measured, "cohorts": len(cohorts), "claims": claims,
            "verdicts": tally, "evidence_regime": regime,
            # A verdict reached from truth is a reference result. It stays in this section
            # so the requirement can be read, and is marked so it cannot be mistaken for
            # something a deployed controller could have established.
            "deployable": regime == "contract_only"}


def coordination_stability(store, epochs, limits, period_s):
    """Behavioural measurement only, with the bounds it was judged against."""
    if not epochs or period_s is None:
        return {"measured": False, "reason": "fewer than two decision epochs were recorded",
                "limits": limits}
    measured, detail = measurements(read_run(store, epochs), limits, period_s)
    return {"measured": True, "limits": limits,
            "metrics": {m["metric"]: m["value"] for m in measured},
            "stability": detail["stability"], "deadlocked_epochs": detail["deadlocked_epochs"],
            "note": detail["note"]}


def missing_evidence(store, epochs, service, stability):
    """Everything the run could not observe, conclude, measure or score."""
    telemetry = []
    abstained = []
    for index in range(epochs):
        for payload in _payloads(store, f"dataset:telemetry:{index}"):
            if payload.kind == "TelemetryBatch" and payload.data["omitted_metrics"]:
                telemetry.append({"epoch": index, "completeness": payload.data["completeness"],
                                  "omitted": payload.data["omitted_metrics"]})
        for payload in _payloads(store, f"dataset:diagnosis:{index}"):
            if payload.kind == "DiagnosisRecord" and not any(
                    h["status"] == "supported" for h in payload.data["hypotheses"]):
                abstained.append(index)
    unmeasured = sorted(f"{name}:{metric}" for name, metrics in service["by_service"].items()
                        for metric, m in metrics.items() if m["quality"] != "measured")
    unmeasured += sorted(f"behaviour:{metric}"
                         for metric, value in stability.get("metrics", {}).items()
                         if value is None)
    censored = []
    if "dataset:result" in set(store.dataset_ids()):
        censored = sorted(c["cohort_id"] for p in _payloads(store, "dataset:result")
                          if p.kind == "ResultRecord" for c in p.data["cohorts"] if c["censored"])
    stages = {}
    for dataset_id in store.dataset_ids():
        data = store.dataset(dataset_id).data
        if data["terminal_status"] in ("rejected", "error", "timeout"):
            code = (data["reason"] or {}).get("code", "unstated")
            stages.setdefault(data["stage_id"], []).append(
                {"dataset": dataset_id, "status": data["terminal_status"], "reason": code})
    return {"telemetry_gaps": telemetry, "diagnosis_without_support": abstained,
            "no_service_extraction": not service["by_service"],
            "unmeasured": unmeasured, "censored_cohorts": censored,
            "inconclusive": [c for c in service["claims"] if c["verdict"] == "inconclusive"],
            "failed_stages": stages}


def privileged_information(store):
    """Every dataset that rests on simulator truth, by stage, with its read count."""
    tainted = {}
    for dataset_id in store.dataset_ids():
        data = store.dataset(dataset_id).data
        if data["information_regime"] == "contract_only":
            continue
        entry = tainted.setdefault(data["stage_id"], {"datasets": 0, "truth_refs": set()})
        entry["datasets"] += 1
        entry["truth_refs"].update(data["privileged_source_refs"])
    by_stage = {stage: {"datasets": entry["datasets"], "truth_refs": len(entry["truth_refs"])}
                for stage, entry in sorted(tainted.items())}
    return {"present": bool(by_stage), "by_stage": by_stage,
            "note": "privileged results are references under simulator truth, "
                    "not evidence any deployed controller could obtain" if by_stage else
                    "no dataset in this run rests on simulator truth"}


def run_report(store, *, limits=None):
    """Assemble the four sections for one recorded run."""
    epochs = _epochs(store)
    period_s = _period(store, epochs)
    limits = limits or stability_limits(period_s or 0)
    runs = {store.dataset(d).data["scope"]["run_id"] for d in store.dataset_ids()}
    service = service_outcomes(store)
    stability = coordination_stability(store, epochs, limits, period_s)
    return {"report_version": REPORT_VERSION, "run_ids": sorted(runs), "epochs": epochs,
            "decision_period_s": period_s,
            "service_outcomes": service,
            "coordination_stability": stability,
            "missing_evidence": missing_evidence(store, epochs, service, stability),
            "privileged_information": privileged_information(store)}


def render(report):
    """The report as text, one section after another and never merged."""
    lines = [f"Run report ({report['report_version']})  {', '.join(report['run_ids'])}",
             f"  {report['epochs']} decision epochs at {report['decision_period_s']} s", ""]
    service = report["service_outcomes"]
    label = "deployable evidence" if service["deployable"] else (
        "PRIVILEGED reference, not deployable evidence" if service["evidence_regime"]
        else "no assurance stage recorded")
    lines.append(f"1. Service outcomes  [{label}]")
    for name, metrics in sorted(service["by_service"].items()):
        delivered = metrics.get("within_age_delivery", {})
        value = delivered.get("value")
        shown = "unknown" if value is None else f"{value:.3f}"
        lines.append(f"   {name:<7} within-age delivery {shown} over "
                     f"{delivered.get('denominator', 0)} generated")
    for claim in service["claims"]:
        lines.append(f"   {claim['requirement_id']:<26}{claim['verdict']:<14}{claim['reason']}")
    lines.append("   " + ", ".join(f"{n} {v}" for v, n in service["verdicts"].items()))

    stability = report["coordination_stability"]
    lines += ["", "2. Coordination stability  [no service outcome consulted]"]
    if stability["measured"]:
        m = stability["metrics"]
        settled = {1: "yes", 0: "no", None: "not established"}[m["coordination_stable"]]
        lines.append(f"   stable {settled}; reversals {m['action_reversals']}, repeats "
                     f"{m['repeated_applications']}, deadlocked epochs {m['deadlocked_epochs']}, "
                     f"starved {m['coordination_starvation_epochs']}")
    else:
        lines.append(f"   not measured: {stability['reason']}")

    missing = report["missing_evidence"]
    lines += ["", "3. Missing evidence  [unknown is not a pass]"]
    lines.append(f"   telemetry gaps in {len(missing['telemetry_gaps'])} epoch(s); "
                 f"diagnosis without support in {len(missing['diagnosis_without_support'])}")
    if missing["no_service_extraction"]:
        lines.append("   no service outcome was extracted")
    lines.append(f"   unmeasured: {', '.join(missing['unmeasured']) or 'none'}")
    lines.append(f"   censored cohorts: {', '.join(missing['censored_cohorts']) or 'none'}")
    lines.append(f"   inconclusive requirements: {len(missing['inconclusive'])}")
    for stage, failures in sorted(missing["failed_stages"].items()):
        lines.append(f"   {stage}: {len(failures)} dataset(s) "
                     f"{sorted({f['status'] + ':' + f['reason'] for f in failures})}")

    privileged = report["privileged_information"]
    lines += ["", "4. Privileged-information results"]
    for stage, entry in privileged["by_stage"].items():
        lines.append(f"   {stage:<11}{entry['datasets']:>4} dataset(s), "
                     f"{entry['truth_refs']} distinct truth read(s)")
    lines.append(f"   {privileged['note']}")
    return "\n".join(lines)
